name: ESP32 S3 MicroPython

permissions:
  contents: write

on:
  push:
    tags:
     - 'v*'
  schedule:
     - cron: '0 0 1 * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IDF_CCACHE_ENABLE: 1
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v7
      
    - name: Clonar Micropython
      run: git clone --depth 1 --recursive https://github.com/micropython/micropython.git
    
    - name: Install yq
      run: sudo apt-get update && sudo apt-get install -y yq

    - id: idf_ver
      name: Extract IDF version from MicroPython workflow
      run: |
        cd micropython
        IDF_VER=$(yq '.env.IDF_NEWEST_VER' .github/workflows/ports_esp32.yml | tr -d '"')
        echo "IDF_VER=$IDF_VER" >> $GITHUB_OUTPUT

    - name: Instalar dependencias
      run: |
       sudo apt update
       sudo apt-get install -y git wget cmake ninja-build ccache
       pip3 install --upgrade pip

    - name: Cache ESP-IDF and environment
      id: cache-esp
      uses: actions/cache@v6
      with:
        path: |
          esp-idf
          ~/.espressif
        key: esp-full-${{ runner.os }}-${{ steps.idf_ver.outputs.IDF_VER }}
        restore-keys: |
          esp-full-${{ runner.os }}-${{ steps.idf_ver.outputs.IDF_VER }}-
  
    - name: Setup ESP-IDF
      run: |
        if [ ! -d "esp-idf" ]; then
          git clone --depth 1 --branch ${{ steps.idf_ver.outputs.IDF_VER }} https://github.com/espressif/esp-idf.git
          git -C esp-idf submodule update --init --recursive --depth=1
        fi
        
        if [ ! -d "$HOME/.espressif/python_env" ]; then
          echo "Instalando entorno virtual de ESP-IDF..."
          ./esp-idf/install.sh
        fi
   
    - name: Set up environment
      run: |
        source esp-idf/export.sh
        echo "IDF_PATH=$GITHUB_WORKSPACE/esp-idf" >> $GITHUB_ENV
        idf.py --version

    - name: Get MicroPython Version from mpconfig.h
      run: |
        cd micropython/
        MAJOR=$(grep -oP '(?<=#define MICROPY_VERSION_MAJOR )[0-9]+' py/mpconfig.h)
        MINOR=$(grep -oP '(?<=#define MICROPY_VERSION_MINOR )[0-9]+' py/mpconfig.h)
        MICRO=$(grep -oP '(?<=#define MICROPY_VERSION_MICRO )[0-9]+' py/mpconfig.h)
        PRERELEASE=$(grep -oP '(?<=#define MICROPY_VERSION_PRERELEASE )[0-9]+' py/mpconfig.h)

        if [ "$PRERELEASE" -eq 1 ]; then
          MPY_VERSION="$MAJOR.$MINOR.$MICRO-preview"
        else
          MPY_VERSION="$MAJOR.$MINOR.$MICRO"
        fi

        echo "MPY_VERSION=$MPY_VERSION" >> $GITHUB_ENV
        
    - name: Create git tag with version
      run: |
        cd micropython
        git tag "v$MPY_VERSION"
        echo "Tag creado: v$MPY_VERSION"
        git tag -l | grep "v$MPY_VERSION"
    
    - name: Compilar MicroPython
      run: |
        source esp-idf/export.sh
        cd ${{ github.workspace }}/micropython
        make -j$(nproc) -C mpy-cross
        make -j$(nproc) -C ports/esp32 submodules
        make -j$(nproc) -C ports/esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT
      
    - name: Mover binarios
      run: |
        mkdir -p ./artifacts
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/firmware.bin artifacts/
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/micropython.bin ./artifacts/
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/bootloader/bootloader.bin ./artifacts/
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/partition_table/partition-table.bin ./artifacts/
        
    - name: Generate Tag
      id: tag
      run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

    - name: Verificar existencia de los cuatro binarios
      run: |
        if [ ! -f ./artifacts/firmware.bin ] || ! -f ./artifacts/micropython.bin ] || [ ! -f ./artifacts/bootloader.bin ] || [ ! -f ./artifacts/partition-table.bin ]; then
          echo "Falta uno o más archivos binarios necesarios, cancelando release."
          exit 1
        fi
      
    - name: GH Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: $TAG_NAME
        name: "MicroPython for ESP32 S3 N16R8 Release version $MPY_VERSION (Build $TAG_NAME)"
        body: |
          Automated release for MicroPython.
          - What we get here:
            - ```firmware.bin, micropython.bin, bootloader.bin and partition-table.bin```
            - `firmware.bin` has `bootloader.bin + partition-table.bin + micropython.bin` in just one file. So this will flash from address `0x0`.
            
          # Instructions
          
          You need to have some dependencies pre-instaled in your OS:
          - Python 3
          - Pip
          - Python VENV
          
          ## Windows or Linux:
          Create Virtual Environment
          ```bash
          python -m venv esp-env
          ```
          
          ### On Windows activate Virtual Environment this way:
          ```bash
          .\esp-env\Scripts\activate
          ```
          ### On Linux activate Virtual Environment this way:
          ```bash
          source esp-env/bin/activate
          ```
          
          ### On Windows or Linux install esptool:
          ```bash
          pip install esptool
          ```
          
          ### Put ESP32 S3 N16R8 in BOOTLOADER MODE:
          - With USB cable on USB COM Port, press BOOT button then RST button, release RST, then release BOOT button. Or unplug, press BOOT button meanwhile you plug in the usb cable to PC or SBC like a Raspberry Pi.
          - Alternative: Use Thonny IDE, plug your ESP32-S3, on Thonny Shell type:
          ```bash
          from machine import bootloader
          ```
          Press ``Enter`` then type:
          ```bash
          bootloader()
          ```
          Press ``Enter`` then just cose Thonny and go to Terminal with Virtual Environment activate.
          
          ### Erase Flash:
          ```bash
          python -m esptool erase-flash
          ```
          
          #### Then Flash:
          - Put 3 binaries in the same folder you are executing the steps, example Downloads folder, you need to be in that folder where are the binaries.
          Yes no big commands, `esptool` recognize `--chip, --port`, give a secure --baudrate` and Micropython detect flash size on first boot.
          
          ```bash
          python -m esptool write-flash 0x0 bootloader.bin 0x8000 partition-table.bin 0x10000 micropython.bin
          ```

          - Or just `firmware.bin` that have 3 bins in 1:
            
          ```python
          python -m esptool write-flash 0x0 firmware.bin
          ```
          
          ### NOTE IN WINDOWS:
          - If you get a PowerShell Scripts Policy Execution Exception that don't let you activate the Virtual Environment:
          
          ```powershell
          .\esp-env\Scripts\activate
          ```
          
          - Then open a Terminal like Administrator and type:
          
          ````bash
          Set-ExecutionPolicy Unrestricted
          ````
          - Close the Terminal now you can activate the Python Virtual Enmvironment
          
        draft: false
        prerelease: false
        files: ./artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
